In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('healthcare-dataset-stroke-data.csv')

In [3]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [9]:
df['bmi']=df['bmi'].fillna(df['bmi'].mean())

In [12]:
df.shape

(5110, 12)

In [14]:
cols=[
    'id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 
    'Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'
]
for col in cols:
    print(f"{col}: {df[col].unique()}")

id: [ 9046 51676 31112 ... 19723 37544 44679]
gender: <StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
age: [6.70e+01 6.10e+01 8.00e+01 4.90e+01 7.90e+01 8.10e+01 7.40e+01 6.90e+01
 5.90e+01 7.80e+01 5.40e+01 5.00e+01 6.40e+01 7.50e+01 6.00e+01 5.70e+01
 7.10e+01 5.20e+01 8.20e+01 6.50e+01 5.80e+01 4.20e+01 4.80e+01 7.20e+01
 6.30e+01 7.60e+01 3.90e+01 7.70e+01 7.30e+01 5.60e+01 4.50e+01 7.00e+01
 6.60e+01 5.10e+01 4.30e+01 6.80e+01 4.70e+01 5.30e+01 3.80e+01 5.50e+01
 1.32e+00 4.60e+01 3.20e+01 1.40e+01 3.00e+00 8.00e+00 3.70e+01 4.00e+01
 3.50e+01 2.00e+01 4.40e+01 2.50e+01 2.70e+01 2.30e+01 1.70e+01 1.30e+01
 4.00e+00 1.60e+01 2.20e+01 3.00e+01 2.90e+01 1.10e+01 2.10e+01 1.80e+01
 3.30e+01 2.40e+01 3.40e+01 3.60e+01 6.40e-01 4.10e+01 8.80e-01 5.00e+00
 2.60e+01 3.10e+01 7.00e+00 1.20e+01 6.20e+01 2.00e+00 9.00e+00 1.50e+01
 2.80e+01 1.00e+01 1.80e+00 3.20e-01 1.08e+00 1.90e+01 6.00e+00 1.16e+00
 1.00e+00 1.40e+00 1.72e+00 2.40e-01 1.64e+00 1.56e+00 7.20e-01 1.88e+00
 1.24e+00 8.00e-01 4.00e-01 8.00e-02 1.48e+00 5.60e-01 4.80e-01 1.60e-01]
hypertension: [0 1]
heart_disease: [1 0]
ever_married: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
work_type: <StringArray>
['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked']
Length: 5, dtype: str
Residence_type: <StringArray>
['Urban', 'Rural']
Length: 2, dtype: str
avg_glucose_level: [228.69 202.21 105.92 ...  82.99 166.29  85.28]
bmi: [36.6        28.89323691 32.5        34.4        24.         29.
 27.4        22.8        24.2        29.7        36.8        27.3
 28.2        30.9        37.5        25.8        37.8        22.4
 48.9        26.6        27.2        23.5        28.3        44.2
 25.4        22.2        30.5        26.5        33.7        23.1
 32.         29.9        23.9        28.5        26.4        20.2
 33.6        38.6        39.2        27.7        31.4        36.5
 33.2        32.8        40.4        25.3        30.2        47.5
 20.3        30.         28.9        28.1        31.1        21.7
 27.         24.1        45.9        44.1        22.9        29.1
 32.3        41.1        25.6        29.8        26.3        26.2
 29.4        24.4        28.         28.8        34.6        19.4
 30.3        41.5        22.6        56.6        27.1        31.3
 31.         31.7        35.8        28.4        20.1        26.7
 38.7        34.9        25.         23.8        21.8        27.5
 24.6        32.9        26.1        31.9        34.1        36.9
 37.3        45.7        34.2        23.6        22.3        37.1
 45.         25.5        30.8        37.4        34.5        27.9
 29.5        46.         42.5        35.5        26.9        45.5
 31.5        33.         23.4        30.7        20.5        21.5
 40.         28.6        42.2        29.6        35.4        16.9
 26.8        39.3        32.6        35.9        21.2        42.4
 40.5        36.7        29.3        19.6        18.         17.6
 19.1        50.1        17.7        54.6        35.         22.
 39.4        19.7        22.5        25.2        41.8        60.9
 23.7        24.5        31.2        16.         31.6        25.1
 24.8        18.3        20.         19.5        36.         35.3
 40.1        43.1        21.4        34.3        27.6        16.5
 24.3        25.7        21.9        38.4        25.9        54.7
 18.6        24.9        48.2        20.7        39.5        23.3
 64.8        35.1        43.6        21.         47.3        16.6
 21.6        15.5        35.6        16.7        41.9        16.4
 17.1        29.2        37.9        44.6        39.6        40.3
 41.6        39.         23.2        18.9        36.1        36.3
 46.5        16.8        46.6        35.2        20.9        13.8
 31.8        15.3        38.2        45.2        17.         49.8
 27.8        60.2        23.         22.1        26.         44.3
 51.         39.7        34.7        21.3        41.2        34.8
 19.2        35.7        40.8        24.7        19.         32.4
 34.         28.7        32.1        51.5        20.4        30.6
 71.9        19.3        40.9        17.2        16.1        16.2
 40.6        18.4        21.1        42.3        32.2        50.2
 17.5        18.7        42.1        47.8        20.8        30.1
 17.3        36.4        12.         36.2        55.7        14.4
 43.         41.7        33.8        43.9        22.7        57.5
 37.         38.5        16.3        44.         32.7        54.2
 40.2        33.3        17.4        41.3        52.3        14.6
 17.8        46.1        33.1        18.1        43.8        50.3
 38.9        43.7        39.9        15.9        19.8        12.3
 78.         38.3        41.         42.6        43.4        15.1
 20.6        33.5        43.2        30.4        38.         33.4
 44.9        44.7        37.6        39.8        53.4        55.2
 42.         37.2        42.8        18.8        42.9        14.3
 37.7        48.4        50.6        46.2        49.5        43.3
 33.9        18.5        44.5        45.4        55.         54.8
 19.9        17.9        15.6        52.8        15.2        66.8
 55.1        18.2        48.5        55.9        57.3        10.3
 14.1        15.7        56.         44.8        13.4        51.8
 38.1        57.7        44.4        38.8        49.3        39.1
 54.         56.1        97.6        53.9        13.7        11.5
 41.4        14.2        49.4        15.4        45.1        49.2
 48.7        53.8        42.7        48.8        52.7        53.5
 50.5        15.8        45.3        14.8        51.9        63.3
 40.7        61.2        48.         46.8        48.3        58.1
 50.4        11.3        12.8        13.5        14.5        15.
 59.7        47.4        52.5        13.2        52.9        61.6
 49.9        54.3        47.9        13.         13.9        50.9
 57.2        64.4        92.         50.8        57.9        45.8
 47.6        14.         46.4        46.9        47.1        13.3
 48.1        51.7        46.3        54.1        14.9       ]
smoking_status: <StringArray>
['formerly smoked', 'never smoked', 'smokes', 'Unknown']
Length: 4, dtype: str
stroke: [1 0]

In [15]:
df=df.drop(columns=['id'])

In [17]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

df[['age', 'bmi', 'avg_glucose_level']]=scaler.fit_transform(df[['age', 'bmi', 'avg_glucose_level']])

In [20]:
df['ever_married']=df['ever_married'].map({'Yes':1, 'No':0})

In [23]:
df=pd.get_dummies(
    df,
    columns=['gender', 'work_type', 'Residence_type', 'smoking_status'],
    drop_first=True
)

In [27]:
print(df['stroke'].value_counts())

stroke
0    4861
1     249
Name: count, dtype: int64

In [28]:
df.head()

,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke,gender_Male,gender_Other,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,0.816895,0,1,1,0.801265,0.301260,1,True,False,False,True,False,False,True,True,False,False
1,0.743652,0,0,1,0.679023,0.212981,1,False,False,False,False,True,False,False,False,True,False
2,0.975586,0,1,1,0.234512,0.254296,1,True,False,False,True,False,False,False,False,True,False
3,0.597168,0,0,1,0.536008,0.276060,1,False,False,False,True,False,False,True,False,False,True
4,0.963379,1,0,1,0.549349,0.156930,1,False,False,False,False,True,False,False,False,True,False

In [30]:
df.to_pickle('cleaned-healthcare-dataset-stroke-data.pkl')